# Generated by Django 3.0.7 on 2020-07-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeGroup",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                (
                    "code_group",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=1000)),
            ],
            options={"db_table": "code_group", "default_permissions": (),},
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
                ("code", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=1000)),
                ("available", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField()),
                ("authority", models.PositiveIntegerField(default=999)),
                (
                    "code_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codes.CodeGroup",
                    ),
                ),
            ],
            options={
                "db_table": "code",
                "default_permissions": (),
                "unique_together": {("code_group", "code")},
            },
        ),
    ]
